const beadUrl = (name) => new URL(`./assets/beads/${name}.png`, import.meta.url).href;
const starBeadUrl = (name) => new URL(`./assets/generated/img-5811-stars-bg-removed/${name}.png`, import.meta.url).href;
const assortedBeadUrl = (name) => new URL(`./assets/generated/assorted-beads-upright/${name}.png`, import.meta.url).href;

export const hardwareColors = [
  { id: "pink", name: "Powder Pink", value: "#f6a8c4", finish: "matte" },
  { id: "gold", name: "Shiny Gold", value: "#d4a847", finish: "metal" },
  { id: "lime", name: "Lime Pop", value: "#b7ef78", finish: "matte" },
  { id: "magenta", name: "Hot Magenta", value: "#d91c77", finish: "matte" },
  { id: "sky", name: "Baby Blue", value: "#9ed6f1", finish: "matte" },
  { id: "mint", name: "Mint", value: "#62d0ac", finish: "matte" },
  { id: "white", name: "Milk White", value: "#f4f1ea", finish: "matte" },
  { id: "cobalt", name: "Cobalt", value: "#1734b7", finish: "matte" },
  { id: "lavender", name: "Lilac", value: "#c9adef", finish: "matte" },
  { id: "black", name: "Soft Black", value: "#171d21", finish: "matte" },
  { id: "silver", name: "Shiny Silver", value: "#c7c9c4", finish: "metal" },
  { id: "orange", name: "Orange", value: "#f47b2b", finish: "matte" },
  { id: "yellow", name: "Sunny Yellow", value: "#f4cc25", finish: "matte" },
  { id: "tan", name: "Taupe Tan", value: "#bca98d", finish: "matte" },
  { id: "brown", name: "Cocoa", value: "#8b523c", finish: "matte" },
  { id: "red", name: "Cherry Red", value: "#e82427", finish: "matte" },
];

export const cordColors = [
  { id: "black-olive", name: "Black Olive", value: "#20251d", accent: "#707768" },
  { id: "orange", name: "Signal Orange", value: "#e55420", accent: "#ff9b42" },
  { id: "hot-pink", name: "Hot Pink", value: "#c41468", accent: "#ff70aa" },
  { id: "silver-gray", name: "Silver Gray", value: "#8b9892", accent: "#d5ddd8" },
  { id: "cool-silver", name: "Cool Silver", value: "#b8c2c4", accent: "#eef4f2" },
  { id: "pearl-silver", name: "Pearl Silver", value: "#d2d1ca", accent: "#faf8ef" },
  { id: "white", name: "White", value: "#f5f2ea", accent: "#ffffff" },
  { id: "cream", name: "Cream", value: "#dfcab1", accent: "#fff0dc" },
  { id: "purple", name: "Purple", value: "#4d3579", accent: "#a980db" },
  { id: "neon-green", name: "Neon Green", value: "#64df1f", accent: "#b6ff70" },
  { id: "dark-teal", name: "Dark Teal", value: "#0b3b36", accent: "#447b72" },
  { id: "red", name: "Red", value: "#df1518", accent: "#ff6a54" },
  { id: "yellow", name: "Yellow", value: "#e7c408", accent: "#ffe95b" },
  { id: "aqua", name: "Aqua", value: "#26c8ce", accent: "#a0fbff" },
  { id: "light-blue", name: "Light Blue", value: "#8fd5ee", accent: "#d9fbff" },
  { id: "blue", name: "Blue", value: "#153f9e", accent: "#6a90ff" },
  { id: "pale-pink", name: "Pale Pink", value: "#dca4bb", accent: "#ffd4e4" },
  { id: "teal", name: "Teal", value: "#009b7b", accent: "#5ff0cf" },
];

export const beads = [
  { id: "star-01-red-top", name: "Red Top Star", shape: "star", src: starBeadUrl("star-01-red-top"), suggestedUse: "strand,charm" },
  { id: "star-02-tan-purple-top", name: "Tan Purple Top Star", shape: "star", src: starBeadUrl("star-02-tan-purple-top"), suggestedUse: "strand,charm" },
  { id: "star-03-sky-red-top", name: "Sky Red Top Star", shape: "star", src: starBeadUrl("star-03-sky-red-top"), suggestedUse: "strand,charm" },
  { id: "star-04-yellow-top-right", name: "Yellow Top Right Star", shape: "star", src: starBeadUrl("star-04-yellow-top-right"), suggestedUse: "strand,charm" },
  { id: "star-05-tan-purple-left", name: "Tan Purple Left Star", shape: "star", src: starBeadUrl("star-05-tan-purple-left"), suggestedUse: "strand,charm" },
  { id: "star-06-black-cream-top", name: "Black Cream Top Star", shape: "star", src: starBeadUrl("star-06-black-cream-top"), suggestedUse: "strand,charm" },
  { id: "star-07-red-brown-top", name: "Red Brown Top Star", shape: "star", src: starBeadUrl("star-07-red-brown-top"), suggestedUse: "strand,charm" },
  { id: "star-08-orange-left", name: "Orange Left Star", shape: "star", src: starBeadUrl("star-08-orange-left"), suggestedUse: "strand,charm" },
  { id: "star-09-mint-speckle-left", name: "Mint Speckle Left Star", shape: "star", src: starBeadUrl("star-09-mint-speckle-left"), suggestedUse: "strand,charm" },
  { id: "star-10-blue-cream-center", name: "Blue Cream Center Star", shape: "star", src: starBeadUrl("star-10-blue-cream-center"), suggestedUse: "strand,charm" },
  { id: "star-11-coral-center", name: "Coral Center Star", shape: "star", src: starBeadUrl("star-11-coral-center"), suggestedUse: "strand,charm" },
  { id: "star-12-black-white-top-right", name: "Black White Top Right Star", shape: "star", src: starBeadUrl("star-12-black-white-top-right"), suggestedUse: "strand,charm" },
  { id: "star-13-yellow-right", name: "Yellow Right Star", shape: "star", src: starBeadUrl("star-13-yellow-right"), suggestedUse: "strand,charm" },
  { id: "star-14-lilac-left", name: "Lilac Left Star", shape: "star", src: starBeadUrl("star-14-lilac-left"), suggestedUse: "strand,charm" },
  { id: "star-15-pale-green-left", name: "Pale Green Left Star", shape: "star", src: starBeadUrl("star-15-pale-green-left"), suggestedUse: "strand,charm" },
  { id: "star-16-aqua-flower-center", name: "Aqua Flower Center Star", shape: "star", src: starBeadUrl("star-16-aqua-flower-center"), suggestedUse: "strand,charm" },
  { id: "star-17-orange-small", name: "Orange Small Star", shape: "star", src: starBeadUrl("star-17-orange-small"), suggestedUse: "strand,charm" },
  { id: "star-18-deep-blue-right", name: "Deep Blue Right Star", shape: "star", src: starBeadUrl("star-18-deep-blue-right"), suggestedUse: "strand,charm" },
  { id: "star-19-teal-bottom-left", name: "Teal Bottom Left Star", shape: "star", src: starBeadUrl("star-19-teal-bottom-left"), suggestedUse: "strand,charm" },
  { id: "star-20-black-cream-bottom", name: "Black Cream Bottom Star", shape: "star", src: starBeadUrl("star-20-black-cream-bottom"), suggestedUse: "strand,charm" },
  { id: "star-21-deep-blue-bottom-center", name: "Deep Blue Bottom Center Star", shape: "star", src: starBeadUrl("star-21-deep-blue-bottom-center"), suggestedUse: "strand,charm" },
  { id: "star-22-deep-blue-bottom-right", name: "Deep Blue Bottom Right Star", shape: "star", src: starBeadUrl("star-22-deep-blue-bottom-right"), suggestedUse: "strand,charm" },
  { id: "star-23-pink-bottom-left", name: "Pink Bottom Left Star", shape: "star", src: starBeadUrl("star-23-pink-bottom-left"), suggestedUse: "strand,charm" },
  { id: "star-24-sky-blue-bottom-left", name: "Sky Blue Bottom Left Star", shape: "star", src: starBeadUrl("star-24-sky-blue-bottom-left"), suggestedUse: "strand,charm" },
  { id: "star-25-brown-cream-bottom", name: "Brown Cream Bottom Star", shape: "star", src: starBeadUrl("star-25-brown-cream-bottom"), suggestedUse: "strand,charm" },
  { id: "star-26-mint-speckle-bottom", name: "Mint Speckle Bottom Star", shape: "star", src: starBeadUrl("star-26-mint-speckle-bottom"), suggestedUse: "strand,charm" },
  { id: "star-27-pale-green-bottom", name: "Pale Green Bottom Star", shape: "star", src: starBeadUrl("star-27-pale-green-bottom"), suggestedUse: "strand,charm" },
  { id: "star-28-black-white-bottom", name: "Black White Bottom Star", shape: "star", src: starBeadUrl("star-28-black-white-bottom"), suggestedUse: "strand,charm" },
  { id: "assorted-01-mint-red-round", name: "Mint Red Round Charm", shape: "round", src: assortedBeadUrl("bead-01-mint-red-round"), suggestedUse: "charm" },
  { id: "assorted-03-olive-splash-cube", name: "Olive Splash Cube Charm", shape: "cube", src: assortedBeadUrl("bead-03-olive-splash-cube"), suggestedUse: "charm" },
  { id: "assorted-05-tortoise-round-top", name: "Tortoise Round Charm", shape: "round", src: assortedBeadUrl("bead-05-tortoise-round-top"), suggestedUse: "charm" },
  { id: "assorted-07-black-silver-round", name: "Black Silver Round Charm", shape: "round", src: assortedBeadUrl("bead-07-black-silver-round"), suggestedUse: "charm" },
  { id: "assorted-08-cream-striped-round", name: "Cream Striped Round Charm", shape: "round", src: assortedBeadUrl("bead-08-cream-striped-round"), suggestedUse: "charm" },
  { id: "assorted-09-cloud-round", name: "Cloud Round Charm", shape: "round", src: assortedBeadUrl("bead-09-cloud-round"), suggestedUse: "charm" },
  { id: "assorted-12-tortoise-round-left", name: "Tortoise Stripe Round Charm", shape: "round", src: assortedBeadUrl("bead-12-tortoise-round-left"), suggestedUse: "charm" },
  { id: "assorted-13-green-cube", name: "Green Cube Charm", shape: "cube", src: assortedBeadUrl("bead-13-green-cube"), suggestedUse: "charm" },
  { id: "assorted-16-blue-diamond", name: "Blue Diamond Charm", shape: "diamond", src: assortedBeadUrl("bead-16-blue-diamond"), suggestedUse: "charm" },
  { id: "assorted-18-cream-cube", name: "Cream Cube Charm", shape: "cube", src: assortedBeadUrl("bead-18-cream-cube"), suggestedUse: "charm" },
  { id: "assorted-20-tortoise-round-mid", name: "Tortoise Round Charm", shape: "round", src: assortedBeadUrl("bead-20-tortoise-round-mid"), suggestedUse: "charm" },
  { id: "assorted-21-light-blue-cube", name: "Light Blue Cube Charm", shape: "cube", src: assortedBeadUrl("bead-21-light-blue-cube"), suggestedUse: "charm" },
  { id: "assorted-23-deep-teal-round", name: "Deep Teal Round Charm", shape: "round", src: assortedBeadUrl("bead-23-deep-teal-round"), suggestedUse: "charm" },
  { id: "assorted-24-pink-cube", name: "Pink Cube Charm", shape: "cube", src: assortedBeadUrl("bead-24-pink-cube"), suggestedUse: "charm" },
  { id: "assorted-26-cream-barrel", name: "Cream Barrel Charm", shape: "barrel", src: assortedBeadUrl("bead-26-cream-barrel"), suggestedUse: "charm" },
  { id: "assorted-27-red-diamond", name: "Red Diamond Charm", shape: "diamond", src: assortedBeadUrl("bead-27-red-diamond"), suggestedUse: "charm" },
  { id: "assorted-28-pink-splash-cube", name: "Pink Splash Cube Charm", shape: "cube", src: assortedBeadUrl("bead-28-pink-splash-cube"), suggestedUse: "charm" },
  { id: "assorted-29-cream-diamond", name: "Cream Diamond Charm", shape: "diamond", src: assortedBeadUrl("bead-29-cream-diamond"), suggestedUse: "charm" },
  { id: "assorted-30-green-round-right", name: "Green Round Charm", shape: "round", src: assortedBeadUrl("bead-30-green-round-right"), suggestedUse: "charm" },
  { id: "assorted-34-blue-black-cube-right", name: "Blue Black Cube Charm", shape: "cube", src: assortedBeadUrl("bead-34-blue-black-cube-right"), suggestedUse: "charm" },
  { id: "assorted-35-green-cream-round", name: "Green Cream Round Charm", shape: "round", src: assortedBeadUrl("bead-35-green-cream-round"), suggestedUse: "charm" },
  { id: "assorted-36-purple-splash-cube", name: "Purple Splash Cube Charm", shape: "cube", src: assortedBeadUrl("bead-36-purple-splash-cube"), suggestedUse: "charm" },
  { id: "assorted-41-cream-cube-right", name: "Cream Cube Charm", shape: "cube", src: assortedBeadUrl("bead-41-cream-cube-right"), suggestedUse: "charm" },
  { id: "assorted-47-black-white-round-bottom", name: "Black White Round Charm", shape: "round", src: assortedBeadUrl("bead-47-black-white-round-bottom"), suggestedUse: "charm" },
  { id: "assorted-50-pink-round-bottom", name: "Pink Round Charm", shape: "round", src: assortedBeadUrl("bead-50-pink-round-bottom"), suggestedUse: "charm" },
  { id: "round-cream-swirl", name: "Cream Swirl Round", shape: "round", src: beadUrl("round-cream-swirl"), suggestedUse: "strand" },
  { id: "round-tortoise-cream", name: "Tortoise Cream Round", shape: "round", src: beadUrl("round-tortoise-cream"), suggestedUse: "strand" },
  { id: "round-aqua-cloud", name: "Aqua Cloud Round", shape: "round", src: beadUrl("round-aqua-cloud"), suggestedUse: "strand" },
  { id: "round-pink-milk", name: "Pink Milk Round", shape: "round", src: beadUrl("round-pink-milk"), suggestedUse: "strand" },
  { id: "round-teal-caramel", name: "Teal Caramel Round", shape: "round", src: beadUrl("round-teal-caramel"), suggestedUse: "strand" },
  { id: "cube-pink-splash", name: "Pink Splash Cube", shape: "cube", src: beadUrl("cube-pink-splash"), suggestedUse: "strand" },
  { id: "cube-ivory-teal-red", name: "Ivory Teal Cube", shape: "cube", src: beadUrl("cube-ivory-teal-red"), suggestedUse: "strand" },
  { id: "cube-blue-black", name: "Blue Black Cube", shape: "cube", src: beadUrl("cube-blue-black"), suggestedUse: "strand" },
  { id: "cube-olive-gloss", name: "Olive Gloss Cube", shape: "cube", src: beadUrl("cube-olive-gloss"), suggestedUse: "strand" },
  { id: "barrel-cream-stripe", name: "Cream Stripe Barrel", shape: "barrel", src: beadUrl("barrel-cream-stripe"), suggestedUse: "strand" },
  { id: "barrel-teal-cream", name: "Teal Cream Barrel", shape: "barrel", src: beadUrl("barrel-teal-cream"), suggestedUse: "strand" },
  { id: "diamond-green-cream", name: "Green Cream Diamond", shape: "diamond", src: beadUrl("diamond-green-cream"), suggestedUse: "strand" },
  { id: "diamond-sky-cream", name: "Sky Cream Diamond", shape: "diamond", src: beadUrl("diamond-sky-cream"), suggestedUse: "strand" },
];

export const defaultDesign = {
  hardwareType: "round",
  hardwareColor: "gold",
  cordColor: "red",
  beads: [],
  charmAttachment: "hardwareLoop",
  charms: [{ id: "charm-1", beadId: "star-04-yellow-top-right", attachmentPoint: "hardwareLoop", x: 318, y: 452 }],
};
